version: '3.7'

services:
  foody.backend:
    container_name: foody.backend
    build:
      context: backend\demo
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    depends_on: 
      - foody.db 
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://foody.db:5432/foody
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: foodytest
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    networks: 
      - foody

  foody.db:
    container_name: foody.db
    image: postgres
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: foodytest
      PGDATA: /data/postgres_foody
    volumes:
      - postgres:/data/postgres_foody
    networks:
      - foody  

  foody.frontend:
    container_name: foody.frontend
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on: 
      - foody.backend 
    networks: 
      - foody  
  
volumes:
  postgres:

networks:
  foody: